module.exports = {
    all: [
        './Gruntfile.js',
        './grunt/**/*.js',
        './src/main/**/*.js',
        './src/test/**/*.js'
    ],
    options: {
        bitwise: true,
        camelcase: true,
        curly: true,
        eqeqeq: true,
        es3: true,
        forin: true,
        freeze: true,
        immed: true,
        latedef: true,
        newcap: true,
        noarg: true,
        node: true,
        noempty: true,
        nonbsp: true,
        nonew: true,
        plusplus: true,
        // quotmark: true,
        undef: true,
        unused: true,
        strict: true,
        maxparams: 4,
        maxdepth: 3,
        maxstatements: 50,
        maxcomplexity: 50,
        maxlen: 200,
        white: true,
        devel: false,
        browser: true,
        indent: 4,
        predef: [
            'require',
            'module',
            '__dirname',
            'jasmine',
            'expect',
            'jasmine',
            'describe',
            'xdescribe',
            'before',
            'beforeEach',
            'after',
            'afterEach',
            'it',
            'xit',
            'it',
            'inject',
            'expect',
            'spyOn',
            'console'
        ]
    }
};